Repository AY2122S2-CS2103T-W15-2/tp, pull requests merged in 2022-03, with the labels that each got.

#46 Split extensions v1.1
  docs/DeveloperGuide.md
Labels: documentation

#47 Modify Person object to fit for client
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Info.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PrevDateMet.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#49 Update GUI
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/hustle_book.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High, type.Task

#50 Add Flag feature for important clients
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FlagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FlagCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Flag.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#55 Test cases for PrevDateMet not implemented and bug found
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/PrevDateMet.java
  src/test/java/seedu/address/model/person/PrevDateMetTest.java
Labels: type.Task, type.Bug, severity.High

#58 Default date should set to the correct date
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/PrevDateMet.java
Labels: type.Bug

#64 Modify delete command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalNames.java
Labels: type.Story, priority.High

#67 Change default of info was not standardised throughout
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Info.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PrevDateMet.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#68 Info class was yet to be tested
  src/test/java/seedu/address/model/person/InfoTest.java
Labels: type.Task

#65 Added SortCommand feature
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Flag.java
  src/main/java/seedu/address/model/person/PrevDateMet.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/PersonPrevDateMetComparator.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#71 Modify edit command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalNames.java
Labels: type.Documentation, type.Story, priority.High

#70 User Guide not updated with the new commands and prefixes
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#73 Update edit command format message
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.Medium

#75 Modify edit info parser
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: priority.Medium

#78 Update Ui.png
  docs/images/Ui.png
Labels: type.Documentation

#79 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#92 Update version number
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#94 Enable assertions in gradle
  build.gradle
Labels: priority.High, type.Task

#95 Add meeting attribute
  src/main/java/seedu/address/model/person/MeetingDate.java
  src/main/java/seedu/address/model/person/MeetingTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/ScheduledMeeting.java
  src/main/java/seedu/address/storage/JsonSerializableHustleBook.java
Labels: type.Story, priority.High

#96 Update implementation of the new client attributes
  docs/DeveloperGuide.md
Labels: type.Documentation

#97 Update flag feature
  src/main/java/seedu/address/logic/commands/FlagCommand.java
  src/main/java/seedu/address/logic/parser/FlagCommandParser.java
  src/main/java/seedu/address/logic/parser/HustleBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Flag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Enhancement

#98 Update DG to include Flag implementation
  docs/DeveloperGuide.md
Labels: type.Documentation

#112 Command to schedule meeting is not implemented
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/HustleBookParser.java
  src/main/java/seedu/address/logic/parser/MeetCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/HustleBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/MeetingTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/ScheduledMeeting.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableHustleBookTest/duplicatePersonHustleBook.json
  src/test/data/JsonSerializableHustleBookTest/typicalPersonsHustleBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#105 Add feature to edit command detect duplicates and let user choose which of the duplicates they want to edit.
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/HustleBookParser.java
  src/main/java/seedu/address/logic/parser/NumberParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/HustleBookParserTest.java
Labels: type.Story, priority.High

#113 Add cancel meeting through meet command
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MeetCommandParser.java
  src/main/java/seedu/address/model/person/MeetingDate.java
  src/main/java/seedu/address/model/person/MeetingTime.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High

#118 Update User Guide
  docs/UserGuide.md
Labels: type.Documentation

#119 Update UserGuide
  docs/UserGuide.md
Labels: type.Documentation

#120 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#124 Update GUI to display salary
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, type.Task

#125 Update GUI display of last date met and upcoming meeting attribute
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, type.Task

#126 Prevent meeting clashes
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/model/HustleBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/ScheduledMeeting.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#128 Update user guide URL in the help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, type.Task

#131 Add feature to display individual help messages
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/HustleBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Flag.java
  src/test/java/seedu/address/logic/parser/HustleBookParserTest.java
Labels: type.Enhancement

#135 Update SortCommand
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/MeetingDate.java
  src/main/java/seedu/address/model/person/MeetingTime.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/person/ScheduledMeeting.java
  src/main/java/seedu/address/model/person/comparators/PersonMeetingComparator.java
  src/main/java/seedu/address/model/person/comparators/PersonSalaryComparator.java
  src/main/java/seedu/address/model/person/exceptions/ComparatorException.java
Labels: priority.High

#145 Fix bug with salary attribute
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Salary.java
Labels: type.Bug, severity.High

#146 Update SortCommand
  src/main/java/seedu/address/model/person/MeetingDate.java
  src/main/java/seedu/address/model/person/MeetingTime.java
Labels: type.Bug, severity.Medium

#147 Add command undo
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/HustleBookParser.java
  src/main/java/seedu/address/model/HustleBookHistory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.Medium

#149 Fix bug with delay in flag and unflag command
  src/main/java/seedu/address/logic/commands/FlagCommand.java
  src/main/java/seedu/address/model/HustleBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug

#155 Fix bug with delay in scheduledMeeting
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/model/HustleBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug

#160 Edit date valid check
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/MeetingDate.java
  src/main/java/seedu/address/model/person/PrevDateMet.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/PrevDateMetTest.java
Labels: type.Bug

#162 Change label behaviour
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug

#166 Update UserGuide
  docs/UserGuide.md
Labels: type.Documentation
