Repository AY2122S2-CS2103T-W15-2/tp, pull requests merged in 2022-04, with the labels that each got.

#216 Update edit command error message
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Documentation

#215 Modify validity check for name
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Documentation, type.Task

#219 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#218 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#221 Fix bug in redo command
  src/main/java/seedu/address/model/HustleBookHistory.java
Labels: type.Bug

#220 Fix usage of flag using add command
  src/main/java/seedu/address/logic/parser/FlagCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Flag.java
Labels: type.Bug

#226 Update PPP Vishwanth2210
  docs/team/vishwanth2210.md
Labels: type.Documentation

#225 Update PPP draft
  docs/team/j4ck990.md
Labels: type.Documentation

#228 Update index
  docs/index.md
Labels: type.Documentation

#233 Add test cases for the new person fields
  src/test/java/seedu/address/model/person/InfoTest.java
  src/test/java/seedu/address/model/person/MeetingDateTest.java
  src/test/java/seedu/address/model/person/MeetingTimeTest.java
  src/test/java/seedu/address/model/person/PrevDateMetTest.java
  src/test/java/seedu/address/model/person/ScheduledMeetingTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#236 Add activity and sequence diagrams for meet command
  docs/diagrams/ScheduleMeetingActivityDiagram.puml
  docs/diagrams/ScheduleMeetingLogicSequenceDiagram.puml
  docs/diagrams/ScheduleMeetingSequenceDiagram.puml
  docs/images/ScheduleMeetingActivityDiagram.png
  docs/images/ScheduleMeetingLogicSequenceDiagram.png
  docs/images/ScheduleMeetingSequenceDiagram.png
Labels: type.Documentation

#237 Update undo and redo commands in ug
  docs/UserGuide.md
  docs/images/redoSuccess.png
  docs/images/undoSuccess.png
Labels: type.Documentation

#241 Phone validity check and Update User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Bug

#238 Fix misbehaviour of long tag and salary
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/SalaryTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.High

#240 Fix Bug after selecting index from multiple names
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FlagCommand.java
Labels: type.Documentation, priority.High, type.Bug

#243 Modify UG structure
  docs/UserGuide.md
Labels: type.Documentation

#245 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#250 Add test cases
  src/main/java/seedu/address/model/HustleBookHistory.java
  src/main/java/seedu/address/model/person/Salary.java
  src/test/java/seedu/address/model/HustleBookHistoryTest.java
  src/test/java/seedu/address/model/person/SalaryTest.java
Labels: type.Task

#259 Update UG
  docs/UserGuide.md
  docs/images/exampleAddCommand.png
  docs/images/exampleMeetCommandCancel.png
  docs/images/exampleMeetCommandSchedule.png
Labels: type.Documentation, priority.High

#263 Update DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#252 Update DG diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ScheduleMeetingLogicSequenceDiagram.puml
  docs/diagrams/ScheduleMeetingSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ScheduleMeetingLogicSequenceDiagram.png
  docs/images/ScheduleMeetingSequenceDiagram.png
Labels: type.Documentation, priority.High, type.Task

#261 Unflag not recognised as valid command for `help` command
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, type.Bug

#266 Add testcases for Flag, Help
  src/main/java/seedu/address/logic/commands/FlagCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/test/java/seedu/address/logic/commands/CommandEnumTest.java
  src/test/java/seedu/address/logic/commands/FlagCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/FlagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HustleBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/FlagTest.java
Labels: type.Task

#272 Add test cases for meet command
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MeetCommandTest.java
  src/test/java/seedu/address/logic/parser/MeetCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#278 Update PPP for Shafik
  docs/team/ad-nap.md
Labels: type.Documentation

#270 Update dg for undo command
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ScheduleMeetingActivityDiagram.puml
  docs/diagrams/UndoClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/ScheduleMeetingActivityDiagram.png
  docs/images/UndoClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: type.Documentation

#276 Fix missing closing div
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#279 Update TestCases for Sort and List
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/comparators/PersonFlagComparator.java
  src/main/java/seedu/address/model/person/comparators/PersonMeetingComparator.java
  src/main/java/seedu/address/model/person/comparators/PersonNameComparator.java
  src/main/java/seedu/address/model/person/comparators/PersonPrevDateMetComparator.java
  src/main/java/seedu/address/model/person/comparators/PersonSalaryComparator.java
  src/main/java/seedu/address/model/util/PersonPrevDateMetComparator.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/HustleBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/comparators/PersonFlagComparatorTest.java
  src/test/java/seedu/address/model/person/comparators/PersonMeetingComparatorTest.java
  src/test/java/seedu/address/model/person/comparators/PersonNameComparatorTest.java
  src/test/java/seedu/address/model/person/comparators/PersonPrevDateMetComparatorTest.java
  src/test/java/seedu/address/model/person/comparators/PersonSalaryComparatorTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#281 Update the correct LoC for HustleBook
  docs/team/ad-nap.md
Labels: type.Documentation

#264 Update DG for SortCommand
  docs/DeveloperGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortLogicSequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortLogicSequenceDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: type.Documentation, priority.High

#283 Update DG for ListCommand
  docs/DeveloperGuide.md
  docs/diagrams/ListLogicSequenceDiagram.puml
  docs/images/ListLogicSequenceDiagram.png
  docs/team/decaxical.md
Labels: type.Documentation, severity.High

#291 Update DG testing appendix
  docs/DeveloperGuide.md
Labels: type.Documentation
